### ISSUE TITLE
Mirror Farewell Release

### ISSUE THREAD

**Issue by zocker1996** [Musta1337/TeknoMW3#3]
Why is the Farewell Release not mirrored in this repo? Since its smaller than 100MB, it should be possible. The new launcher is also mirrored here. It would be nice to have all files together.

**Comment by SoyRA** [comment]
Maybe it's because I use it in the browser, because if I try to upload it: _Yowza, that’s a big file. Try again with a file smaller than 25MB._

I'll do the pull later and edit the link on the wiki.

**Comment by EPNW** [comment]
Ah yes, the browser allowes only files up to 25mb. But using a git client you can upload up to 100mb. Thanks for accepting the pull 👍
